<a href="https://colab.research.google.com/github/UsaMasa/Python/blob/master/Numpy%E7%B7%B4%E7%BF%92%E3%83%8E%E3%83%BC%E3%83%88%E3%83%96%E3%83%83%E3%82%AF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy練習用ノートブック

## 自習用
便利な関数置き場

In [0]:
import numpy as np

## np.squeeze
不要な次元を削減する

参考：　https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html

In [3]:
x = np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [4]:
np.squeeze(x,axis=0).shape

(3, 1)

In [5]:
np.squeeze(x,axis=-1).shape

(1, 3)

## reshape(-1)

reshapeの一つのサイズが決まっているときに、もう一方を-1にすると、-1には元の形状から推測された値が入る。

なお、配列等のindexとして-1を指定する際は配列の最後を表す。混同に注意。

参考：　https://qiita.com/guitar_char/items/deb49d5a433a2c8a8ed4

In [6]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
x.shape

(3, 4)

In [7]:
#行ベクトルになり、列サイズは元の形状から推測されてreshapeされる
x.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
#列数2のみが決まり、行数は元の形状から推測される
x.reshape(-1,2)

## 行列の操作


参考　：　https://qiita.com/supersaiakujin/items/d63c73bb7b5aac43898a

In [27]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
print(X[1:3,0:2])
#1行目から3-1行目までと、0列目から1列目までを抜き出す

[[ 5  6]
 [10 11]]


In [23]:
print(X[1])#X[1,], X[1,:]も同じ
#行の抽出

[5 6 7 8 9]


In [24]:
print(X[:, 1])
#列の抽出。ただしこの時結果が一次元のnumpy arrayになるので、行列演算に使う場合は注意

[ 1  6 11 16 21]


In [29]:
X[X%2==0]=0
print(X)
#条件を満たすものを全て0に置き換える

[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


In [30]:
X[np.ix_([1,3],[0,2])]
#1行目か3行目かつ、0列目か2列目

array([[ 5,  7],
       [15, 17]])

In [31]:
i,j = np.where(X!=0)
X[i,j]
#条件を満たすものを抽出する

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [35]:
a = np.array([0,1,2])
b = np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1 2]
 [4 5 6]]
[0 1 2 4 5 6]


In [39]:
#a.reshape(len(a),1)
#b.reshape(len(b),1)
np.hstack((a.reshape(len(a),1),b.reshape(len(b),1)))

array([[0, 4],
       [1, 5],
       [2, 6]])

In [41]:
a.reshape(1, len(a)).transpose()
#転置。a.tranpose()だけだと何も起きない

array([[0],
       [1],
       [2]])

## one-hot表現への変換
np.arrayをone-hot表現に変換する

参考：　https://tutorialmore.com/questions-771930.htm

In [0]:
def one_hot(a, num_classes):
    return np.squeeze(np.eye(num_classes)[a.reshape(-1)])

In [8]:
a = np.array([[1],[0],[3]])

array([[1],
       [0],
       [3]])

In [17]:
one_hot(a,4)

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [16]:
one_hot(np.array([0,1]),2)

array([[1., 0.],
       [0., 1.]])