<a href="https://colab.research.google.com/github/UsaMasa/Python/blob/master/Numpy%E7%B7%B4%E7%BF%92%E3%83%8E%E3%83%BC%E3%83%88%E3%83%96%E3%83%83%E3%82%AF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy練習用ノートブック

## 自習用
便利な関数置き場

In [0]:
import numpy as np

## np.squeeze
不要な次元を削減する

参考：　https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html

In [0]:
x = np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [0]:
np.squeeze(x,axis=0).shape

(3, 1)

In [0]:
np.squeeze(x,axis=-1).shape

(1, 3)

## reshape(-1)

reshapeの一つのサイズが決まっているときに、もう一方を-1にすると、-1には元の形状から推測された値が入る。

なお、配列等のindexとして-1を指定する際は配列の最後を表す。混同に注意。

参考：　https://qiita.com/guitar_char/items/deb49d5a433a2c8a8ed4

In [0]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
x.shape

(3, 4)

In [0]:
#行ベクトルになり、列サイズは元の形状から推測されてreshapeされる
x.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
#列数2のみが決まり、行数は元の形状から推測される
x.reshape(-1,2)

## 行列の操作


参考　：　https://qiita.com/supersaiakujin/items/d63c73bb7b5aac43898a

In [0]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [0]:
print(X[1:3,0:2])
#1行目から3-1行目までと、0列目から1列目までを抜き出す

[[ 5  6]
 [10 11]]


In [0]:
print(X[1])#X[1,], X[1,:]も同じ
#行の抽出

[5 6 7 8 9]


In [0]:
print(X[:, 1])
#列の抽出。ただしこの時結果が一次元のnumpy arrayになるので、行列演算に使う場合は注意

[ 1  6 11 16 21]


In [0]:
X[X%2==0]=0
print(X)
#条件を満たすものを全て0に置き換える

[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


In [0]:
X[np.ix_([1,3],[0,2])]
#1行目か3行目かつ、0列目か2列目

array([[ 5,  7],
       [15, 17]])

In [0]:
i,j = np.where(X!=0)
X[i,j]
#条件を満たすものを抽出する

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
a = np.array([0,1,2])
b = np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1 2]
 [4 5 6]]
[0 1 2 4 5 6]


In [0]:
#a.reshape(len(a),1)
#b.reshape(len(b),1)
np.hstack((a.reshape(len(a),1),b.reshape(len(b),1)))

array([[0, 4],
       [1, 5],
       [2, 6]])

In [0]:
a.reshape(1, len(a)).transpose()
#転置。a.tranpose()だけだと何も起きない

array([[0],
       [1],
       [2]])

## 配列の条件抽出

### np.where(条件式, x, y)
条件式を満たす場合はx、満たさない場合はyを返す。指定しない場合はインデックスを返す。
参考　：　https://note.nkmk.me/python-numpy-where/


In [18]:
a = np.arange(9).reshape(3,3)
print(a)
print(a<4)
print(np.where(a<4, -1, 100))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]


In [22]:
print(np.where(a<4))
#各次元に対するtupleとして与えられる
#list, zip と組み合わせることで、座標取得も可能
print(list(zip(*np.where(a<4))))

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))
[(0, 0), (0, 1), (0, 2), (1, 0)]


In [35]:
#要素を上手く抜き出すことが出来るが、型に注意する必要はある
a_1d = np.random.randint(0,10,10)
print(a_1d)
print(np.where(a_1d<3))
print(type(np.where(a_1d)))
print(np.where(a_1d<3)[0])
print(type(np.where(a_1d)[0]))
print(type(np.where(a_1d<3)[0].tolist()))

[2 0 0 6 4 1 5 0 3 5]
(array([0, 1, 2, 5, 7]),)
<class 'tuple'>
[0 1 2 5 7]
<class 'numpy.ndarray'>
<class 'list'>


## one-hot表現への変換
np.arrayをone-hot表現に変換する

参考：　https://tutorialmore.com/questions-771930.htm

In [0]:
def one_hot(a, num_classes):
    return np.squeeze(np.eye(num_classes)[a.reshape(-1)])

In [0]:
a = np.array([[1],[0],[3]])

array([[1],
       [0],
       [3]])

In [0]:
one_hot(a,4)

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [0]:
one_hot(np.array([0,1]),2)

array([[1., 0.],
       [0., 1.]])

## sortについて

参考　：　https://deepage.net/features/numpy-sort.html

In [37]:
a = np.random.randint(0,100, size = 20)
print(a)

[40 63 60 73 90 17 52 49 12 11 42 89 34 32 71  9 89 18 75 65]


In [4]:
np.sort(a) #昇順にソートされる

array([ 0,  0,  8,  9, 23, 23, 26, 28, 35, 40, 50, 58, 67, 71, 73, 85, 90,
       92, 93, 95])

In [5]:
b = np.array([1,3,2])
np.argsort(b) # sort結果のインデックスの配列を返す

array([0, 2, 1])

## 訓練データとテストデータの分割


### scikit-learnが必要


参考　：　https://note.nkmk.me/python-sklearn-train-test-split/

In [12]:
from sklearn.model_selection import train_test_split
a = np.arange(10) # [0,1,2, ... 9]
print(train_test_split(a))
print(type(train_test_split(a)))
a_train, a_test = train_test_split(a)
print(a_train)
print(a_test)
# デフォルトでは25%（test_size = 0.25, テスト側サンプル数の小数点切り上げ）がテスト用になる。test_size=7みたいに個数で指定も可能
# デフォルトではshuffle = True だが、Falseにしても良い。shuffleの乱数シードはrandom_state=0等で固定可能

[array([6, 1, 7, 9, 0, 5, 2]), array([4, 3, 8])]
<class 'list'>
[9 4 0 8 7 1 3]
[5 2 6]


In [13]:
#複数のデータの分割も可能
X = np.arange(20).reshape(2,10).T
y = np.arange(10)
print(X)
print(y)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y)
print(X_train)
print(y_train)

[[ 5 15]
 [ 3 13]
 [ 6 16]
 [ 8 18]
 [ 4 14]
 [ 2 12]
 [ 7 17]]
[5 3 6 8 4 2 7]
